/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.TenantDetailAPIDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for AllTenantsStatusAPIDTO
 */
public class AllTenantsStatusAPIDTOTest {
    private final AllTenantsStatusAPIDTO model = new AllTenantsStatusAPIDTO();

    /**
     * Model tests for AllTenantsStatusAPIDTO
     */
    @Test
    public void testAllTenantsStatusAPIDTO() {
        // TODO: test AllTenantsStatusAPIDTO
    }

    /**
     * Test the property 'tenants'
     */
    @Test
    public void tenantsTest() {
        // TODO: test tenants
    }

    /**
     * Test the property 'limit'
     */
    @Test
    public void limitTest() {
        // TODO: test limit
    }

    /**
     * Test the property 'start'
     */
    @Test
    public void startTest() {
        // TODO: test start
    }

}
