/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for MetricValidationSummaryDTO
 */
public class MetricValidationSummaryDTOTest {
    private final MetricValidationSummaryDTO model = new MetricValidationSummaryDTO();

    /**
     * Model tests for MetricValidationSummaryDTO
     */
    @Test
    public void testMetricValidationSummaryDTO() {
        // TODO: test MetricValidationSummaryDTO
    }

    /**
     * Test the property 'symbolName'
     */
    @Test
    public void symbolNameTest() {
        // TODO: test symbolName
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'value'
     */
    @Test
    public void valueTest() {
        // TODO: test value
    }

}
