/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.CustomTenantPropertyDTO;
import com.konfigthis.client.model.TenantModuleDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantDetailAPIDTO
 */
public class TenantDetailAPIDTOTest {
    private final TenantDetailAPIDTO model = new TenantDetailAPIDTO();

    /**
     * Model tests for TenantDetailAPIDTO
     */
    @Test
    public void testTenantDetailAPIDTO() {
        // TODO: test TenantDetailAPIDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'tenantDisplayName'
     */
    @Test
    public void tenantDisplayNameTest() {
        // TODO: test tenantDisplayName
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'provisionDate'
     */
    @Test
    public void provisionDateTest() {
        // TODO: test provisionDate
    }

    /**
     * Test the property 'currentDataVersion'
     */
    @Test
    public void currentDataVersionTest() {
        // TODO: test currentDataVersion
    }

    /**
     * Test the property 'dataVersionDate'
     */
    @Test
    public void dataVersionDateTest() {
        // TODO: test dataVersionDate
    }

    /**
     * Test the property 'modules'
     */
    @Test
    public void modulesTest() {
        // TODO: test modules
    }

    /**
     * Test the property 'industryCode'
     */
    @Test
    public void industryCodeTest() {
        // TODO: test industryCode
    }

    /**
     * Test the property 'canAdministerOtherTenants'
     */
    @Test
    public void canAdministerOtherTenantsTest() {
        // TODO: test canAdministerOtherTenants
    }

    /**
     * Test the property 'embeddableDomains'
     */
    @Test
    public void embeddableDomainsTest() {
        // TODO: test embeddableDomains
    }

    /**
     * Test the property 'customProperties'
     */
    @Test
    public void customPropertiesTest() {
        // TODO: test customProperties
    }

    /**
     * Test the property 'ssoInstanceIssuers'
     */
    @Test
    public void ssoInstanceIssuersTest() {
        // TODO: test ssoInstanceIssuers
    }

    /**
     * Test the property 'vanityUrlName'
     */
    @Test
    public void vanityUrlNameTest() {
        // TODO: test vanityUrlName
    }

}
