/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.BusinessLocationDTO;
import com.konfigthis.client.model.CustomPropertyDTO;
import com.konfigthis.client.model.HomeAnalysisByUserGroupDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantManagementAPIUpdateRequestDTO
 */
public class TenantManagementAPIUpdateRequestDTOTest {
    private final TenantManagementAPIUpdateRequestDTO model = new TenantManagementAPIUpdateRequestDTO();

    /**
     * Model tests for TenantManagementAPIUpdateRequestDTO
     */
    @Test
    public void testTenantManagementAPIUpdateRequestDTO() {
        // TODO: test TenantManagementAPIUpdateRequestDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'tenantDisplayName'
     */
    @Test
    public void tenantDisplayNameTest() {
        // TODO: test tenantDisplayName
    }

    /**
     * Test the property 'tenantShortName'
     */
    @Test
    public void tenantShortNameTest() {
        // TODO: test tenantShortName
    }

    /**
     * Test the property 'vanityUrlName'
     */
    @Test
    public void vanityUrlNameTest() {
        // TODO: test vanityUrlName
    }

    /**
     * Test the property 'industryCode'
     */
    @Test
    public void industryCodeTest() {
        // TODO: test industryCode
    }

    /**
     * Test the property 'primaryBusinessLocation'
     */
    @Test
    public void primaryBusinessLocationTest() {
        // TODO: test primaryBusinessLocation
    }

    /**
     * Test the property 'purchasedModules'
     */
    @Test
    public void purchasedModulesTest() {
        // TODO: test purchasedModules
    }

    /**
     * Test the property 'embeddableDomains'
     */
    @Test
    public void embeddableDomainsTest() {
        // TODO: test embeddableDomains
    }

    /**
     * Test the property 'customProperties'
     */
    @Test
    public void customPropertiesTest() {
        // TODO: test customProperties
    }

    /**
     * Test the property 'ssoInstanceIssuers'
     */
    @Test
    public void ssoInstanceIssuersTest() {
        // TODO: test ssoInstanceIssuers
    }

    /**
     * Test the property 'homeAnalysisId'
     */
    @Test
    public void homeAnalysisIdTest() {
        // TODO: test homeAnalysisId
    }

    /**
     * Test the property 'homeAnalysisByUserGroup'
     */
    @Test
    public void homeAnalysisByUserGroupTest() {
        // TODO: test homeAnalysisByUserGroup
    }

    /**
     * Test the property 'updateAction'
     */
    @Test
    public void updateActionTest() {
        // TODO: test updateAction
    }

    /**
     * Test the property 'enabled'
     */
    @Test
    public void enabledTest() {
        // TODO: test enabled
    }

    /**
     * Test the property 'clickThroughLink'
     */
    @Test
    public void clickThroughLinkTest() {
        // TODO: test clickThroughLink
    }

}
