/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MetricValidationSummaryDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantPreviewEntriesSummaryDTO
 */
public class TenantPreviewEntriesSummaryDTOTest {
    private final TenantPreviewEntriesSummaryDTO model = new TenantPreviewEntriesSummaryDTO();

    /**
     * Model tests for TenantPreviewEntriesSummaryDTO
     */
    @Test
    public void testTenantPreviewEntriesSummaryDTO() {
        // TODO: test TenantPreviewEntriesSummaryDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'dataVersion'
     */
    @Test
    public void dataVersionTest() {
        // TODO: test dataVersion
    }

    /**
     * Test the property 'dataVersionDate'
     */
    @Test
    public void dataVersionDateTest() {
        // TODO: test dataVersionDate
    }

    /**
     * Test the property 'metrics'
     */
    @Test
    public void metricsTest() {
        // TODO: test metrics
    }

}
