/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TenantStatusAPIDTO
 */
public class TenantStatusAPIDTOTest {
    private final TenantStatusAPIDTO model = new TenantStatusAPIDTO();

    /**
     * Model tests for TenantStatusAPIDTO
     */
    @Test
    public void testTenantStatusAPIDTO() {
        // TODO: test TenantStatusAPIDTO
    }

    /**
     * Test the property 'tenantCode'
     */
    @Test
    public void tenantCodeTest() {
        // TODO: test tenantCode
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'tenantDisplayName'
     */
    @Test
    public void tenantDisplayNameTest() {
        // TODO: test tenantDisplayName
    }

    /**
     * Test the property 'canAdministerOtherTenants'
     */
    @Test
    public void canAdministerOtherTenantsTest() {
        // TODO: test canAdministerOtherTenants
    }

}
