/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for UpdateTenantModel
 */
public class UpdateTenantModelTest {
    private final UpdateTenantModel model = new UpdateTenantModel();

    /**
     * Model tests for UpdateTenantModel
     */
    @Test
    public void testUpdateTenantModel() {
        // TODO: test UpdateTenantModel
    }

    /**
     * Test the property 'tenantDisplayName'
     */
    @Test
    public void tenantDisplayNameTest() {
        // TODO: test tenantDisplayName
    }

    /**
     * Test the property 'industryCode'
     */
    @Test
    public void industryCodeTest() {
        // TODO: test industryCode
    }

    /**
     * Test the property 'purchasedModules'
     */
    @Test
    public void purchasedModulesTest() {
        // TODO: test purchasedModules
    }

    /**
     * Test the property 'embeddableDomains'
     */
    @Test
    public void embeddableDomainsTest() {
        // TODO: test embeddableDomains
    }

    /**
     * Test the property 'customProperties'
     */
    @Test
    public void customPropertiesTest() {
        // TODO: test customProperties
    }

    /**
     * Test the property 'ssoInstanceIssuers'
     */
    @Test
    public void ssoInstanceIssuersTest() {
        // TODO: test ssoInstanceIssuers
    }

}
