/*
 * Visier Tenant Management APIs
 * Visier APIs for managing tenants
 *
 * The version of the OpenAPI document: 22222222.99201.1200
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.MetricValidationSummaryDTO;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * TenantPreviewEntriesSummaryDTO
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class TenantPreviewEntriesSummaryDTO {
  public static final String SERIALIZED_NAME_TENANT_CODE = "tenantCode";
  @SerializedName(SERIALIZED_NAME_TENANT_CODE)
  private String tenantCode;

  public static final String SERIALIZED_NAME_DATA_VERSION = "dataVersion";
  @SerializedName(SERIALIZED_NAME_DATA_VERSION)
  private String dataVersion;

  public static final String SERIALIZED_NAME_DATA_VERSION_DATE = "dataVersionDate";
  @SerializedName(SERIALIZED_NAME_DATA_VERSION_DATE)
  private String dataVersionDate;

  public static final String SERIALIZED_NAME_METRICS = "metrics";
  @SerializedName(SERIALIZED_NAME_METRICS)
  private List<MetricValidationSummaryDTO> metrics = null;

  public TenantPreviewEntriesSummaryDTO() {
  }

  public TenantPreviewEntriesSummaryDTO tenantCode(String tenantCode) {
    
    
    
    
    this.tenantCode = tenantCode;
    return this;
  }

   /**
   * The tenant code of the analytic tenant. For example, \&quot;WFF_j1r~i1o\&quot;.
   * @return tenantCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The tenant code of the analytic tenant. For example, \"WFF_j1r~i1o\".")

  public String getTenantCode() {
    return tenantCode;
  }


  public void setTenantCode(String tenantCode) {
    
    
    
    this.tenantCode = tenantCode;
  }


  public TenantPreviewEntriesSummaryDTO dataVersion(String dataVersion) {
    
    
    
    
    this.dataVersion = dataVersion;
    return this;
  }

   /**
   * The data version ID.
   * @return dataVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The data version ID.")

  public String getDataVersion() {
    return dataVersion;
  }


  public void setDataVersion(String dataVersion) {
    
    
    
    this.dataVersion = dataVersion;
  }


  public TenantPreviewEntriesSummaryDTO dataVersionDate(String dataVersionDate) {
    
    
    
    
    this.dataVersionDate = dataVersionDate;
    return this;
  }

   /**
   * The date that the data version was created.
   * @return dataVersionDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The date that the data version was created.")

  public String getDataVersionDate() {
    return dataVersionDate;
  }


  public void setDataVersionDate(String dataVersionDate) {
    
    
    
    this.dataVersionDate = dataVersionDate;
  }


  public TenantPreviewEntriesSummaryDTO metrics(List<MetricValidationSummaryDTO> metrics) {
    
    
    
    
    this.metrics = metrics;
    return this;
  }

  public TenantPreviewEntriesSummaryDTO addMetricsItem(MetricValidationSummaryDTO metricsItem) {
    if (this.metrics == null) {
      this.metrics = new ArrayList<>();
    }
    this.metrics.add(metricsItem);
    return this;
  }

   /**
   * A list of metrics and their values.
   * @return metrics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of metrics and their values.")

  public List<MetricValidationSummaryDTO> getMetrics() {
    return metrics;
  }


  public void setMetrics(List<MetricValidationSummaryDTO> metrics) {
    
    
    
    this.metrics = metrics;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the TenantPreviewEntriesSummaryDTO instance itself
   */
  public TenantPreviewEntriesSummaryDTO putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TenantPreviewEntriesSummaryDTO tenantPreviewEntriesSummaryDTO = (TenantPreviewEntriesSummaryDTO) o;
    return Objects.equals(this.tenantCode, tenantPreviewEntriesSummaryDTO.tenantCode) &&
        Objects.equals(this.dataVersion, tenantPreviewEntriesSummaryDTO.dataVersion) &&
        Objects.equals(this.dataVersionDate, tenantPreviewEntriesSummaryDTO.dataVersionDate) &&
        Objects.equals(this.metrics, tenantPreviewEntriesSummaryDTO.metrics)&&
        Objects.equals(this.additionalProperties, tenantPreviewEntriesSummaryDTO.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tenantCode, dataVersion, dataVersionDate, metrics, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TenantPreviewEntriesSummaryDTO {\n");
    sb.append("    tenantCode: ").append(toIndentedString(tenantCode)).append("\n");
    sb.append("    dataVersion: ").append(toIndentedString(dataVersion)).append("\n");
    sb.append("    dataVersionDate: ").append(toIndentedString(dataVersionDate)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("tenantCode");
    openapiFields.add("dataVersion");
    openapiFields.add("dataVersionDate");
    openapiFields.add("metrics");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to TenantPreviewEntriesSummaryDTO
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!TenantPreviewEntriesSummaryDTO.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in TenantPreviewEntriesSummaryDTO is not found in the empty JSON string", TenantPreviewEntriesSummaryDTO.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("tenantCode") != null && !jsonObj.get("tenantCode").isJsonNull()) && !jsonObj.get("tenantCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `tenantCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("tenantCode").toString()));
      }
      if ((jsonObj.get("dataVersion") != null && !jsonObj.get("dataVersion").isJsonNull()) && !jsonObj.get("dataVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataVersion").toString()));
      }
      if ((jsonObj.get("dataVersionDate") != null && !jsonObj.get("dataVersionDate").isJsonNull()) && !jsonObj.get("dataVersionDate").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `dataVersionDate` to be a primitive type in the JSON string but got `%s`", jsonObj.get("dataVersionDate").toString()));
      }
      if (jsonObj.get("metrics") != null && !jsonObj.get("metrics").isJsonNull()) {
        JsonArray jsonArraymetrics = jsonObj.getAsJsonArray("metrics");
        if (jsonArraymetrics != null) {
          // ensure the json data is an array
          if (!jsonObj.get("metrics").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `metrics` to be an array in the JSON string but got `%s`", jsonObj.get("metrics").toString()));
          }

          // validate the optional field `metrics` (array)
          for (int i = 0; i < jsonArraymetrics.size(); i++) {
            MetricValidationSummaryDTO.validateJsonObject(jsonArraymetrics.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!TenantPreviewEntriesSummaryDTO.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'TenantPreviewEntriesSummaryDTO' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<TenantPreviewEntriesSummaryDTO> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(TenantPreviewEntriesSummaryDTO.class));

       return (TypeAdapter<T>) new TypeAdapter<TenantPreviewEntriesSummaryDTO>() {
           @Override
           public void write(JsonWriter out, TenantPreviewEntriesSummaryDTO value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public TenantPreviewEntriesSummaryDTO read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             TenantPreviewEntriesSummaryDTO instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of TenantPreviewEntriesSummaryDTO given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of TenantPreviewEntriesSummaryDTO
  * @throws IOException if the JSON string is invalid with respect to TenantPreviewEntriesSummaryDTO
  */
  public static TenantPreviewEntriesSummaryDTO fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, TenantPreviewEntriesSummaryDTO.class);
  }

 /**
  * Convert an instance of TenantPreviewEntriesSummaryDTO to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

